version: "3"

services:
  hugo:
    container_name: hugo_theme_iris
    image: ghcr.io/peaceiris/hugo:${HUGO_VERSION}-mod
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src/hugo-theme-iris
      - ${HUGO_CACHEDIR}:/root/.cache/hugo
    environment:
      - HUGO_CACHEDIR=/root/.cache/hugo
    stdin_open: true
    tty: true
    working_dir: /src/hugo-theme-iris/exampleSite
    entrypoint: bash
