name: "Setup Hugo envs"
description: "A composite action to setup Hugo environments variables"
runs:
  using: "composite"
  steps:
    - name: Set envs
      shell: bash
      run: |
        echo "::set-output name=HUGO_VERSION::$(make get-hugo-version)"
        echo "::set-output name=GO_VERSION::$(make get-go-version)"
        echo "::set-output name=NODE_VERSION::$(cat .nvmrc)"
