name: Dependabot

on:
  pull_request_target:

jobs:
  approve:
    runs-on: ubuntu-20.04
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.1

      - uses: actions/checkout@v3

      - name: Approve
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout "${PR_URL}"
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ]; then
            gh pr review --approve "${PR_URL}"
          else
            echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi

  merge:
    needs: approve
    runs-on: ubuntu-20.04
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.1

      - name: Enable auto-merge for Dependabot PRs
        if: |
          steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: gh pr merge --auto --squash "${PR_URL}"
