name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  main:
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/workflows/create-release-npm@v0.14.1
        with:
          draft: ''
          prerelease: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
