name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-18.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: peaceiris/workflows/create-release-npm@v0.10.0
        with:
          draft: ''
          prerelease: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
