name: Release

on:
  workflow_dispatch:
    inputs:
      semver_type:
        description: "Semver type"
        required: true
        type: "choice"
        options:
          - "patch"
          - "minor"
          # - "major"
        default: "patch"

jobs:
  main:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: peaceiris/actions-github-app-token@v1
        id: app
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app.outputs.token }}
          fetch-depth: 0

      - uses: peaceiris/workflows/setup-git@v0.19.1

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
        run: |
          CURRENT_TAG=$(git describe --abbrev=0)
          NEW_VERSION=$(npm_config_yes=true npx semver "${CURRENT_TAG}" --increment ${{ github.event.inputs.semver_type }})
          NEW_TAG="v${NEW_VERSION}"
          RELEASE_TITLE="Release ${NEW_TAG}"
          git tag -a "${NEW_TAG}" -m "${RELEASE_TITLE}"
          git push origin "${NEW_TAG}"
          gh release create "${NEW_TAG}" --title "${RELEASE_TITLE}" --generate-notes --discussion-category "Announcements"
